spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://babysteps.c6vpbkzcxdkw.ap-northeast-2.rds.amazonaws.com:3306/moti?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: asdf1234
  jpa:
    database: mysql
    properties:
      hibernate:
        use_sql_comments : true
        show_sql: true #쿼리 출력
        format_sql: true # 쿼리 출력시 포맷 정렬되도록 설정
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: dontreply20230111
    password: dzoozeyrejfcqfuu
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  redis:
    host: moti.today
    password: asdf1234
    port: 6379
file:
  path: C:/Users/SSAFY/ideaProjects/S08P12A509/upload
cloud:
  aws:
    credentials:
      access-key: AKIA6EDQJKQRUPDNEE4F
      secret-key: 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
    s3:
      bucket : motiimages
    region:
      static: ap-northeast-2
    stack:
      auto: false

